### PR TITLE
sc_qspi_nor: Add read mask to register verification

### LINKED ISSUE #5: Bootloader fails to detect correct config memory selection due to unmasked register check
This issue was discovered when attempting to boot from Configuration Memory 1.

Currently, the bootloader blindly tries to switch to Configuration Memory 0, regardless of which memory was actually used during boot. 

That said, the issue here that we are checking every bit of the register instead of checking the one we modify.

```
*** Booting Zephyr OS build v4.1.0-5645-g9075d5335596 ***
SC-OBC Module A1 Bootloader Ver 1.0.0
Load from Configuration Memory address : 0x01a00000
Err: read32  [0x4F000010] 0x00001000 (exp:0x00000000) (retry:100000)!!! Verify failed: retry count: 100000
!!! Can not select Config Memory 0
Failed to copy the Zephyr application from Config memory to HRMEM.
```

Log Breakdown
```
0x4F000010 = address of the Configuration Flash Memory Register
Read value: 0x00001000
Expected value: 0x00000000
```

The difference is bit 12, which is 1 in the read value. That value shouldn't be compare here.

Bit 12 corresponds to the CFGBOOTMEM field — a read-only bit that indicates which config memory was used to boot.
In this case, the system booted from Configuration Memory 1, so CFGBOOTMEM = 1.

See SC-OBC documentation :
https://spacecubics.github.io/sc-docs/scobc-a1-fpga-technical-reference-manual/latest/index.html#_configuration_flash_memory_register_offset_0x0010

Root Cause

The bootloader currently compares the entire register value to 0x00000000, expecting all bits to be cleared after selecting Config 0.

But that’s incorrect, because some bits are read-only and reflect hardware state that can’t be changed — like CFGBOOTMEM.

So, even though the Config Memory Select (bit 4) is set correctly, the presence of CFGBOOTMEM = 1 causes the check to fail.

This leads to:
- Unnecessary retries
- Incorrect assumption that Config 0 failed
- Boot failure, even though the hardware is behaving correctly

Proposed Fix
Instead of checking the entire 32-bit value, we should only check the relevant writable bits.

### PR DESCRIPTION
**Pull request by moonlight83340**
- Modified `verify()` function to accept an additional `read_mask` argument, allowing masked comparisons of register values.

- Updated all calls to `verify()` to pass appropriate `GENMASK()` values for precise bit checking, avoiding false negatives due to unrelated bits.

- Improved reliability of configuration memory selection, QSPI idle checks, and interrupt status validation by ensuring only relevant bits are compared.

Fixes #5 

After fix, boot without any error when selecting config memory 1 (It change to config memory 0 without trouble)
```
*** Booting Zephyr OS build v4.2.0-1141-g2aca4ef0c236 ***
SC-OBC Module A1 Bootloader Ver 1.0.0
Load from Configuration Memory address : 0x01a00000
*** Booting Zephyr OS build sc-norflash-v1.0.0-1-gc3e086418799 ***
Hello World, scobc_a1@2.0.0/designstart_fpga_cortex_m3
```

### CODE REVIEW

**Comment by sasataku** [comment]
Please clearly describe the specific issue that occurred and clarify that this PR is intended to fix it.
 I recommend creating an issue for it.

File: src/sc_qspi_nor.c [hunk 1]
```diff
@@ -65,11 +65,13 @@ static inline void write32(uint32_t addr, uint32_t val)
 	sys_write32(val, addr);
 }
 
-static bool verify(uint32_t addr, uint32_t exp, uint32_t retry)
+static bool verify(uint32_t addr, uint32_t exp, uint32_t read_mask, uint32_t retry)
 {
 	uint32_t regval;
 
 	regval = sys_read32(addr);
+	regval &= read_mask;
```
Comment (sasataku) [inline src/sc_qspi_nor.c:73]: I'm just asking out of curiosity — was there a reason you didn't write it in a single line?
( `sys_read32(addr) & read_mask` )

File: src/sc_qspi_nor.c [hunk 2]
```diff
@@ -104,15 +107,15 @@ static bool qspi_select_mem(uint32_t base, uint8_t mem_no, uint32_t *spi_ss)
 		if (mem_no == SC_DATA_MEM0) {
 			/* Select Config Memory 0 */
 			write32(SCOBCA1_FPGA_SYSREG_CFGMEMCTL, 0x00);
-			if (!verify(SCOBCA1_FPGA_SYSREG_CFGMEMCTL, 0x00,
+			if (!verify(SCOBCA1_FPGA_SYSREG_CFGMEMCTL, 0x00, GENMASK(5, 4),
```
Comment (sasataku) [inline src/sc_qspi_nor.c:110]: Let's give the ”GENMASK" a proper name and turn it into a macro.

**Review by sasataku — CHANGES_REQUESTED** [review]

File: src/sc_qspi_nor.c (hunk 1 above)
Comment (moonlight83340) [reply src/sc_qspi_nor.c:73]: I wrote it in two lines for clarity and easier debugging, but you're right we can do it in a single line.

File: src/sc_qspi_nor.c (hunk 2 above)
Comment (sasataku) [reply src/sc_qspi_nor.c:110]: With GENMASK(5, 4), it's not clear which specific bits of the FPGA register are being masked.
I believe giving the macro a descriptive name that indicates which bits are being referenced would help improve code readability.
Do I really need to check the FPGA register documentation myself to figure out what bits 4 and 5 represent?

File: src/sc_qspi_nor.c (hunk 1 above)
Comment (moonlight83340) [reply src/sc_qspi_nor.c]: I change it to a single line.

File: src/sc_qspi_nor.c (hunk 2 above)
Comment (moonlight83340) [reply src/sc_qspi_nor.c]: I added defines for bits 5 and 4 of the config memory select register to make the purpose of the GENMASK clearer. I hope this improves readability.

File: src/sc_qspi_nor.c [hunk 3]
```diff
@@ -13,20 +13,21 @@
...
+#define SCQSPI_FIFORR_OFFSET      (0x0014)      /* QSPI FIFO Reset Register */
+#define SCQSPI_ISR_OFFSET         (0x0020)      /* QSPI Interrupt Status Register */
+#define SCQSPI_IER_OFFSET         (0x0024)      /* QSPI Interrupt Enable Register */
+#define SCQSPI_CCR_OFFSET         (0x0030)      /* QSPI Clock Control Register */
+#define SCQSPI_DCMSR_OFFSET       (0x0034)      /* QSPI Data Capture Mode Setting Register */
+#define SCQSPI_FTLSR_OFFSET       (0x0038)      /* QSPI FIFO Threshold Level Setting Register */
+#define SCQSPI_VER_OFFSET         (0xF000)      /* QSPI Controller IP Version Register */
+#define SYSREG_CFGMEMCTL_OFFSET   (0x0010)      /* Configuration Flash Memory Register */
+#define SYSREG_BOOTSTS_OFFSET     (0x0014)      /* Boot Status Register */
+#define SYSREG_CFGMEMSEL_MON_MASK GENMASK(5, 4) /* CFGMEMSEL and CFGMEMMON bits mask */
```
Comment (sasataku) [inline src/sc_qspi_nor.c:30]: This area is for `OFFSET`.
Please move to the bottom.

**Review by sasataku — CHANGES_REQUESTED** [review]
